version: 2.1
jobs:
  build:
    working_directory: ~/circleci-pajaritos
    docker:
      - image: circleci/python:3.8.3
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.8/site-packages
      - restore_cache:
          key: deps0-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install dependencies
          command: |
            sudo pip install pipenv
            pipenv install
            pipenv install --dev
      - save_cache:
          key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.8/site-packages"
      - run:
          name: Tests
          command: |
            pipenv run nosetests --with-coverage --cover-package=pajaritos
      - store_test_results:
          path: test-results
